const doctors = [
  {
    name: "Dr. Aarav Sharma",
    profilePicture: "https://randomuser.me/api/portraits/men/1.jpg",
    about:
      "Experienced cardiologist specializing in interventional procedures and preventive heart care.",
    specialty: "Cardiology",
    experience: 12,
    degree: "MD Cardiology",
    location: "Delhi",
    hospital: "Apollo Hospital",
    rate: 1200,
    availability: true,
    modeOfConsultation: "Online",
    language: "Hindi",
  },
  {
    name: "Dr. Priya Verma",
    profilePicture: "https://randomuser.me/api/portraits/women/2.jpg",
    about:
      "Dermatologist with a passion for cosmetic and clinical dermatology, helping patients achieve healthy skin.",
    specialty: "Dermatology",
    experience: 8,
    degree: "MD Dermatology",
    location: "Mumbai",
    hospital: "Fortis Hospital",
    rate: 900,
    availability: true,
    modeOfConsultation: "Offline",
    language: "English",
  },
  {
    name: "Dr. Rohan Gupta",
    profilePicture: "https://randomuser.me/api/portraits/men/3.jpg",
    about:
      "Neurologist with expertise in treating epilepsy, stroke, and neurodegenerative disorders.",
    specialty: "Neurology",
    experience: 15,
    degree: "DM Neurology",
    location: "Bangalore",
    hospital: "Manipal Hospital",
    rate: 1500,
    availability: false,
    modeOfConsultation: "Online",
    language: "Kannada",
  },
  {
    name: "Dr. Sneha Patel",
    profilePicture: "https://randomuser.me/api/portraits/women/4.jpg",
    about:
      "Pediatrician dedicated to child health, growth, and development with a gentle approach.",
    specialty: "Pediatrics",
    experience: 10,
    degree: "MD Pediatrics",
    location: "Ahmedabad",
    hospital: "CIMS Hospital",
    rate: 800,
    availability: true,
    modeOfConsultation: "Offline",
    language: "Gujarati",
  },
  {
    name: "Dr. Vikram Singh",
    profilePicture: "https://randomuser.me/api/portraits/men/5.jpg",
    about:
      "Orthopedic surgeon skilled in joint replacement and sports injury management.",
    specialty: "Orthopedics",
    experience: 18,
    degree: "MS Orthopedics",
    location: "Chennai",
    hospital: "MIOT Hospital",
    rate: 1300,
    availability: true,
    modeOfConsultation: "Online",
    language: "Tamil",
  },
  {
    name: "Dr. Anjali Mehra",
    profilePicture: "https://randomuser.me/api/portraits/women/6.jpg",
    about:
      "Gynecologist with a focus on women's reproductive health and minimally invasive procedures.",
    specialty: "Gynecology",
    experience: 11,
    degree: "MD Gynecology",
    location: "Pune",
    hospital: "Ruby Hall Clinic",
    rate: 1100,
    availability: false,
    modeOfConsultation: "Offline",
    language: "Marathi",
  },
  {
    name: "Dr. Rajesh Kumar",
    profilePicture: "https://randomuser.me/api/portraits/men/7.jpg",
    about:
      "General physician with broad experience in internal medicine and chronic disease management.",
    specialty: "General Medicine",
    experience: 9,
    degree: "MD General Medicine",
    location: "Hyderabad",
    hospital: "Yashoda Hospital",
    rate: 700,
    availability: true,
    modeOfConsultation: "Online",
    language: "Telugu",
  },
  {
    name: "Dr. Meera Nair",
    profilePicture: "https://randomuser.me/api/portraits/women/8.jpg",
    about:
      "Ophthalmologist specializing in cataract and refractive surgeries, committed to restoring vision.",
    specialty: "Ophthalmology",
    experience: 13,
    degree: "MS Ophthalmology",
    location: "Kochi",
    hospital: "Aster Medcity",
    rate: 950,
    availability: true,
    modeOfConsultation: "Offline",
    language: "Malayalam",
  },
  {
    name: "Dr. Sandeep Joshi",
    profilePicture: "https://randomuser.me/api/portraits/men/9.jpg",
    about:
      "ENT specialist with expertise in sinus surgery and hearing disorders.",
    specialty: "ENT",
    experience: 7,
    degree: "MS ENT",
    location: "Jaipur",
    hospital: "SMS Hospital",
    rate: 600,
    availability: false,
    modeOfConsultation: "Online",
    language: "Hindi",
  },
  {
    name: "Dr. Kavita Rao",
    profilePicture: "https://randomuser.me/api/portraits/women/10.jpg",
    about:
      "Psychiatrist passionate about mental health awareness and holistic patient care.",
    specialty: "Psychiatry",
    experience: 14,
    degree: "MD Psychiatry",
    location: "Kolkata",
    hospital: "AMRI Hospital",
    rate: 1400,
    availability: true,
    modeOfConsultation: "Offline",
    language: "Bengali",
  },
  {
    name: "Dr. Amitabh Mishra",
    profilePicture: "https://randomuser.me/api/portraits/men/11.jpg",
    about:
      "Urologist with advanced skills in endourology and kidney stone management.",
    specialty: "Urology",
    experience: 16,
    degree: "MCh Urology",
    location: "Lucknow",
    hospital: "SGPGI",
    rate: 1600,
    availability: true,
    modeOfConsultation: "Online",
    language: "Hindi",
  },
  {
    name: "Dr. Shalini Desai",
    profilePicture: "https://randomuser.me/api/portraits/women/12.jpg",
    about:
      "Oncologist dedicated to cancer prevention, early detection, and personalized treatment plans.",
    specialty: "Oncology",
    experience: 12,
    degree: "DM Oncology",
    location: "Surat",
    hospital: "HCG Hospital",
    rate: 1700,
    availability: false,
    modeOfConsultation: "Offline",
    language: "Gujarati",
  },
  {
    name: "Dr. Nikhil Reddy",
    profilePicture: "https://randomuser.me/api/portraits/men/13.jpg",
    about:
      "Nephrologist with a focus on dialysis, kidney transplantation, and hypertension management.",
    specialty: "Nephrology",
    experience: 10,
    degree: "DM Nephrology",
    location: "Vijayawada",
    hospital: "Ramesh Hospitals",
    rate: 1250,
    availability: true,
    modeOfConsultation: "Online",
    language: "Telugu",
  },
  {
    name: "Dr. Pooja Sinha",
    profilePicture: "https://randomuser.me/api/portraits/women/14.jpg",
    about:
      "Endocrinologist experienced in managing diabetes, thyroid, and metabolic disorders.",
    specialty: "Endocrinology",
    experience: 8,
    degree: "DM Endocrinology",
    location: "Patna",
    hospital: "Paras HMRI Hospital",
    rate: 1050,
    availability: true,
    modeOfConsultation: "Offline",
    language: "Hindi",
  },
  {
    name: "Dr. Manish Chawla",
    profilePicture: "https://randomuser.me/api/portraits/men/15.jpg",
    about: "Pulmonologist with expertise in asthma, COPD, and sleep medicine.",
    specialty: "Pulmonology",
    experience: 9,
    degree: "MD Pulmonology",
    location: "Bhopal",
    hospital: "AIIMS Bhopal",
    rate: 950,
    availability: false,
    modeOfConsultation: "Online",
    language: "Hindi",
  },
  {
    name: "Dr. Ritu Kapoor",
    profilePicture: "https://randomuser.me/api/portraits/women/16.jpg",
    about:
      "Rheumatologist specializing in autoimmune diseases and arthritis care.",
    specialty: "Rheumatology",
    experience: 7,
    degree: "DM Rheumatology",
    location: "Chandigarh",
    hospital: "PGIMER",
    rate: 1150,
    availability: true,
    modeOfConsultation: "Offline",
    language: "Punjabi",
  },
  {
    name: "Dr. Arvind Iyer",
    profilePicture: "https://randomuser.me/api/portraits/men/17.jpg",
    about:
      "Gastroenterologist with a keen interest in liver diseases and endoscopic procedures.",
    specialty: "Gastroenterology",
    experience: 13,
    degree: "DM Gastroenterology",
    location: "Coimbatore",
    hospital: "GKNM Hospital",
    rate: 1350,
    availability: true,
    modeOfConsultation: "Online",
    language: "Tamil",
  },
  {
    name: "Dr. Swati Bhatt",
    profilePicture: "https://randomuser.me/api/portraits/women/18.jpg",
    about:
      "Hematologist with experience in blood disorders and bone marrow transplantation.",
    specialty: "Hematology",
    experience: 6,
    degree: "DM Hematology",
    location: "Indore",
    hospital: "CHL Hospital",
    rate: 950,
    availability: true,
    modeOfConsultation: "Offline",
    language: "Hindi",
  },
  {
    name: "Dr. Prakash Shetty",
    profilePicture: "https://randomuser.me/api/portraits/men/19.jpg",
    about:
      "Plastic surgeon with expertise in reconstructive and cosmetic surgery.",
    specialty: "Plastic Surgery",
    experience: 11,
    degree: "MCh Plastic Surgery",
    location: "Mangalore",
    hospital: "KMC Hospital",
    rate: 2000,
    availability: false,
    modeOfConsultation: "Online",
    language: "Kannada",
  },
  {
    name: "Dr. Neha Agarwal",
    profilePicture: "https://randomuser.me/api/portraits/women/20.jpg",
    about:
      "Radiologist skilled in advanced imaging techniques and diagnostic accuracy.",
    specialty: "Radiology",
    experience: 8,
    degree: "MD Radiology",
    location: "Nagpur",
    hospital: "Wockhardt Hospital",
    rate: 1000,
    availability: true,
    modeOfConsultation: "Offline",
    language: "Marathi",
  },
  {
    name: "Dr. Ishaan Malhotra",
    profilePicture: "https://randomuser.me/api/portraits/men/21.jpg",
    about:
      "Anesthesiologist with experience in pain management and perioperative care.",
    specialty: "Anesthesiology",
    experience: 10,
    degree: "MD Anesthesiology",
    location: "Delhi",
    hospital: "Max Hospital",
    rate: 950,
    availability: true,
    modeOfConsultation: "Online",
    language: "Hindi",
  },
  {
    name: "Dr. Radhika Menon",
    profilePicture: "https://randomuser.me/api/portraits/women/22.jpg",
    about:
      "Pathologist with a focus on cancer diagnostics and laboratory medicine.",
    specialty: "Pathology",
    experience: 7,
    degree: "MD Pathology",
    location: "Kochi",
    hospital: "Lakeshore Hospital",
    rate: 800,
    availability: false,
    modeOfConsultation: "Offline",
    language: "Malayalam",
  },
  {
    name: "Dr. Aditya Chauhan",
    profilePicture: "https://randomuser.me/api/portraits/men/23.jpg",
    about:
      "Ophthalmologist with a special interest in glaucoma and retinal diseases.",
    specialty: "Ophthalmology",
    experience: 12,
    degree: "MS Ophthalmology",
    location: "Lucknow",
    hospital: "King George's Medical University",
    rate: 1100,
    availability: true,
    modeOfConsultation: "Online",
    language: "Hindi",
  },
  {
    name: "Dr. Simran Kaur",
    profilePicture: "https://randomuser.me/api/portraits/women/24.jpg",
    about:
      "Dentist with expertise in restorative dentistry and smile makeovers.",
    specialty: "Dentistry",
    experience: 9,
    degree: "BDS",
    location: "Amritsar",
    hospital: "Amandeep Hospital",
    rate: 700,
    availability: true,
    modeOfConsultation: "Offline",
    language: "Punjabi",
  },
  {
    name: "Dr. Arjun Deshmukh",
    profilePicture: "https://randomuser.me/api/portraits/men/25.jpg",
    about:
      "Psychiatrist with a focus on adolescent mental health and addiction treatment.",
    specialty: "Psychiatry",
    experience: 14,
    degree: "MD Psychiatry",
    location: "Pune",
    hospital: "Jehangir Hospital",
    rate: 1200,
    availability: false,
    modeOfConsultation: "Online",
    language: "Marathi",
  },
  {
    name: "Dr. Nisha Reddy",
    profilePicture: "https://randomuser.me/api/portraits/women/26.jpg",
    about:
      "Obstetrician with experience in high-risk pregnancies and prenatal care.",
    specialty: "Obstetrics",
    experience: 11,
    degree: "MD Obstetrics",
    location: "Hyderabad",
    hospital: "Care Hospitals",
    rate: 1150,
    availability: true,
    modeOfConsultation: "Offline",
    language: "Telugu",
  },
  {
    name: "Dr. Karan Patel",
    profilePicture: "https://randomuser.me/api/portraits/men/27.jpg",
    about:
      "Orthopedic surgeon with a focus on trauma and pediatric orthopedics.",
    specialty: "Orthopedics",
    experience: 13,
    degree: "MS Orthopedics",
    location: "Vadodara",
    hospital: "Sterling Hospital",
    rate: 1300,
    availability: true,
    modeOfConsultation: "Online",
    language: "Gujarati",
  },
  {
    name: "Dr. Shruti Das",
    profilePicture: "https://randomuser.me/api/portraits/women/28.jpg",
    about:
      "Pediatrician with a special interest in immunization and child nutrition.",
    specialty: "Pediatrics",
    experience: 8,
    degree: "MD Pediatrics",
    location: "Kolkata",
    hospital: "Belle Vue Clinic",
    rate: 900,
    availability: false,
    modeOfConsultation: "Offline",
    language: "Bengali",
  },
  {
    name: "Dr. Mohit Suri",
    profilePicture: "https://randomuser.me/api/portraits/men/29.jpg",
    about:
      "Dermatologist with experience in pediatric dermatology and laser treatments.",
    specialty: "Dermatology",
    experience: 6,
    degree: "MD Dermatology",
    location: "Chandigarh",
    hospital: "Ivy Hospital",
    rate: 850,
    availability: true,
    modeOfConsultation: "Online",
    language: "Hindi",
  },
];

export default doctors;
